/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // docs: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  docs: [
      'introduction',
      {
          type: 'category',
          label: 'Concepts',
          items: [
              'Concepts/data-format',
              'Concepts/schema',
              'Concepts/action-time',
              'Concepts/filters',
              'Concepts/compression',
              'Concepts/input-format',
              'Concepts/storage-service'
          ]
      },
      {
          type: "category",
          label: "Tutorials",
          items: [
              'tutorials/tutorial-input-format'
          ]
      },
  ]
};

module.exports = sidebars;
