/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    // The docs entrance is in the docusaurus.config.js

    // By default, Docusaurus generates a sidebar from the docs folder structure
    // docs: [{type: 'autogenerated', dirName: '.'}],

    // But you can create a sidebar manually
    docs: [
        {
            type: "category",
            label: "Getting started",
            items: [
                'GettingStarted/Introduction',
                'GettingStarted/Quickstart',
            ]
        },
        'DataLoader',
        {
            type: "category",
            label: "Tutorials",
            items: [
                'Tutorials/tutorial-csv'
            ]
        },
        'Application/Application',
    ]
};

module.exports = sidebars;
